name: Sync Image to Aliyun Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Aliyun Docker Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-rabdabzjv0hyxneu.cn-hangzhou.personal.cr.aliyuncs.com
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Verify Docker Login and Info
      run: |
        docker info
        docker images

    - name: Sync Image to Aliyun
      run: |
        image_name="ghcr.io/open-webui/open-webui"
        tag="ollama"  # 指定你要同步的标签

        aliyun_repo="crpi-rabdabzjv0hyxneu.cn-hangzhou.personal.cr.aliyuncs.com/lglhg/${image_name}"

        # 从 GHCR 拉取镜像
        docker pull "ghcr.io/${image_name}:${tag}"

        # 标记并推送到阿里云
        docker tag "ghcr.io/${image_name}:${tag}" "${aliyun_repo}:${tag}"
        docker push "${aliyun_repo}:${tag}"
