name: Sync Image to Aliyun (No Login Example)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    # 获取所有 Docker Hub 镜像版本，并推送到阿里云
    - name: Sync All Versions of Image to Aliyun
      run: |
        # 镜像名称
        image_name="mongo"  # 你可以根据需要修改为其他镜像名
        aliyun_repo="crpi-rabdabzjv0hyxneu.cn-hangzhou.personal.cr.aliyuncs.com/lglhg/mongo"
        
        # 获取镜像所有标签的 API
        tags=$(curl -s "https://registry.hub.docker.com/v2/repositories/library/${image_name}/tags/" | jq -r '.results[].name')

        # 拉取并推送每个标签
        for tag in $tags; do
          echo "正在同步镜像 ${image_name}:${tag} ..."
          
          # 拉取并推送镜像到阿里云
          docker pull "docker.io/library/${image_name}:${tag}"
          docker tag "docker.io/library/${image_name}:${tag}" "${aliyun_repo}:${tag}"
          docker push "${aliyun_repo}:${tag}"
        done
