name: Sync Image to Aliyun Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    # 设置 Docker Hub 登录
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: docker.io
        username: ${{secrets.DOCKER1_USERNAME}}
        password: ${{secrets.DOCKER1_PASSWORD}}
        logout: false

    # 设置阿里云登录
    - name: Login to Aliyun Docker Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-rabdabzjv0hyxneu.cn-hangzhou.personal.cr.aliyuncs.com
        username: ${{secrets.ALIYUN_USERNAME}}
        password: ${{secrets.ALIYUN_PASSWORD}}
        logout: false

    # 获取 GitHub 容器注册表（GHCR）的所有标签，并同步到阿里云
    - name: Sync All Versions of Image to Aliyun
      run: |
        # 镜像名称和阿里云目标仓库
        image_name="open-webui/open-webui"
        tag="ollama"  # 指定你想要同步的标签

        aliyun_repo="crpi-rabdabzjv0hyxneu.cn-hangzhou.personal.cr.aliyuncs.com/lglhg/${image_name}"

        # 拉取 GitHub 容器注册表中的镜像
        docker pull "ghcr.io/${image_name}:${tag}"

        # 标记并推送到阿里云仓库，标签不变
        docker tag "ghcr.io/${image_name}:${tag}" "${aliyun_repo}:${tag}"
        docker push "${aliyun_repo}:${tag}"
